-- Run these in Supabase SQL Editor

create table profiles (
  id uuid references auth.users on delete cascade primary key,
  full_name text,
  role text check (role in ('admin', 'guru', 'siswa')),
  created_at timestamp default now()
);

create table berita (
  id bigint generated by default as identity primary key,
  title text,
  content text,
  created_at timestamp default now()
);

create table spmb_applications (
  id bigint generated by default as identity primary key,
  name text,
  email text,
  phone text,
  status text default 'pending',
  created_at timestamp default now()
);

-- Trigger to insert profile when auth user created
create function handle_new_user()
returns trigger as $$
begin
  insert into profiles (id, full_name, role)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'role');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function handle_new_user();
